excluded:
  - Project.swift
  - SupportingFiles/Generated/R.generated.swift
  - Testing
  - SupportingFiles/Generated/Needle.generated.swift
  - Pulsetip/SupportingFiles/Generated/Needle.generated.swift
  - Project.swift
  - ThirdParties/

disabled_rules:
   - trailing_whitespace
   - void_return
   - multiple_closures_with_trailing_closure
   - trailing_comma
   - nesting
   - trailing_newline
   - identifier_name

opt_in_rules:
  - anyobject_protocol
  - closure_spacing
  - collection_alignment
  - convenience_type
  - cyclomatic_complexity
  - discouraged_object_literal
  - empty_string
  - redundant_string_enum_value
  - toggle_bool
  - uiimage
  - uistoryboard
  - uinib
  - uistoryboardsegue

identifier_name:
  excluded:
    - id
    - URL
    - x
    - y
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6
    - s1
    - s2
    - p1
    - p2
    - c2

custom_rules:
  uiimage:
      included: ".*.swift"
      name: "UIImage Hardcoded"
      regex: UIImage\(named:\ ?\"(.*)\"\)
      message: "Hardcoded UIImage strings are not allowed."
      severity: error
  uistoryboard:
    included: ".*.swift"
    name: "UIStoryboard Hardcoded"
    regex: UIStoryboard\(name:\ ?\"(.*)\"\)
    message: "Hardcoded UIStoryboard strings are not allowed."
    severity: error
  uinib:
    included: ".*.swift"
    name: "UINib Hardcoded"
    regex: \(nibName:\ ?\"(.*)\"\)
    message: "Hardcoded UINib strings are not allowed."
    severity: error
  uistoryboardsegue:
    included: ".*.swift"
    name: "UIStoryboardSegue Hardcoded"
    regex: performSegue\(withIdentifier:\ ?\"(.*)\"\)
    message: "Hardcoded UIStoryboardSegue strings are not allowed."
    severity: error

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
