// File automatically generated by tuist
//
//  MainScreen.swift
//  MainScreen
//
//  Created by Wojciech Konury on 02/05/2021.
//

import SwiftUI
import Vendors
import ComposableArchitecture

public struct MainScreen: View {
    let store: Store<RootState, RootAction>
    
    public init(store: Store<RootState, RootAction>) {
        self.store = store
    }
    
    public var body: some View {
        WithViewStore(self.store) { viewStore in
            Circle()
                .fill(Color.blue)
                .frame(
                    width: 100,
                    height: 100,
                    alignment: .center)
                .padding()
                .onAppear { viewStore.send(.onAppear) }
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        MainScreen(store: .init(
                        initialState: RootState(),
                        reducer: rootReducer,
                        environment: RootEnvironment()))
    }
}
