// File automatically generated by tuist
//
//  MainScreen.swift
//  MainScreen
//
//  Created by Wojciech Konury on 02/05/2021.
//

import SwiftUI
import Vendors
import ComposableArchitecture
import QoyanUI

public struct MainScreen: View {
    let store: Store<RootState, RootAction>
    
    public init(store: Store<RootState, RootAction>) {
        self.store = store
    }
    
    public var body: some View {
        WithViewStore(self.store) { viewStore in
            VStack {
                Text("Current Hydration")
                    .font(Font(QoyanUI.QoyanUIFontFamily.RoundedMplus1c.regular.font(size: 25.0)))
                    .foregroundColor(Color(QoyanUI.QoyanUIAsset.purpleDark.color))
                    .padding(.bottom, 25)
                
                IntakeView(store: self.store.scope(
                            state: \.intakeState,
                            action: RootAction.intakeAction))
                Spacer()
                
                AmountPickerView(store: self.store.scope(
                                    state: \.amountPickerState,
                                    action: RootAction.amountPickerAction))
                    .padding(.horizontal, 35)

            }
            .padding()
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        MainScreen(store: .init(
                    initialState: RootState(),
                    reducer: rootReducer,
                    environment: RootEnvironment()))
    }
}
