
import ProjectDescription

let nameAttribute: Template.Attribute = .required("name")

let exampleContents =
    """
    // File automatically generated by tuist
    """


let template = Template(
    description: "Feature-framework template",
    attributes: [
        nameAttribute,
        .optional("platform", default: "iOS"),
    ],
    files: [
        .string(path: "Qoyan/Core/\(nameAttribute)/Sources/\(nameAttribute).swift", contents: exampleContents),
        // Sources
        .file(
            path: "Qoyan/Core/\(nameAttribute)/Project.swift",
            templatePath: "../Stencils/foundation_project.stencil"),
        // Tests
        .file(
            path: "Qoyan/Core/\(nameAttribute)/Tests/\(nameAttribute)Tests.swift",
            templatePath: "../Stencils/tests_contents.stencil"),
    ])
